### ISSUE TITLE
Another error that not clear what's wrong.

### ISSUE THREAD

**Issue by qolina** [ljhgabe/BERT-ParsCit#4]
```
[2022-06-08 08:12:42,389][src.training_pipeline][INFO] - Instantiating datamodule <src.datamodules.bert_parscit_datamodule.BERTParsCitDataModule>
[2022-06-08 08:12:42,395][src.training_pipeline][INFO] - Instantiating model <src.models.bert_parscit_module.BertParsCitLitModule>
Error executing job with overrides: []
Error locating target 'src.models.bert_parscit_module.BertParsCitLitModule', see chained exception above.
full_key: model

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by ljhgabe** [comment]
Hi Yanxia,

Yes, as I mentioned earlier, this can happen time to time for any possible packages. In your case I think it is probably because of the wandb issue. You can try to pip install wandb to see whether this error persists.

For future issues like this, in the training_pipeline.py, instead of using hydra to instantiate the model, you can instantiate the model your self by writing something like `model = BertParsCItLitModule(...)`, and you may observe the full stack trace.

**Comment by qolina** [comment]
Is it correct to run training with `python train.py`.  Are there any other necessary parameters?

**Comment by ljhgabe** [comment]
Yup it is correct. You can follow the instructions on the original lightning-hydra-template for more information. For example, if you want to train using 1 gpu, you can specify `python train.py trainer.gpus=1` and to see full stack trace, you can specify `python train.py +HYDRA_FULL_ERROR=1` although I don't think it works in this case.
